[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim.git'
hook_add = 'source ~/.vim/vimrc/autoload/plugins/unite.vim'
depends = 'neomru.vim'

# color scheme
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo =  'tomasr/molokai'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'source ~/.vim/vimrc/autoload/plugins/vim-indent-guides.vim'


#[[plugins]]
#repo = 'powerline/powerline'
#rtp = 'powerline/bindings/vim/'
[[plugins]]
repo = 'vim-airline/vim-airline'

# 末尾の無駄なスペースをハイライト／削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# VimでGit操作
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

# 構文チェック
[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = 'source ~/.vim/vimrc/autoload/plugins/syntastic.vim'

[[plugins]]
repo = 'vim-latex/vim-latex'

# .tmux.conf ハイライト
[[plugins]]
repo = 'tmux-plugins/vim-tmux'

# Markdown preview :PrevimOpen
[[plugins]]
repo = 'kannokanno/previm'
hook_add = 'source ~/.vim/vimrc/autoload/plugins/previm.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'pangloss/vim-javascript'
